dbt_escape_room:
  target: dev
  outputs:
    dev:
      type: fabric
      driver: "ODBC Driver 18 for SQL Server"
      server: "REDACTED_SERVER"
      database: "REDACTED_DATABASE"
      port: 1433
      schema: "{{ env_var('DBT_SCHEMA', 'dbt_' ~ env_var('USERNAME', 'dev')) }}"
      authentication: CLI
      threads: 4
